config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'}
  #devise_for :users, controllers: {sessions: 'sessions'}
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :users do
      collection do
      end
    end

    resources :products do
      collection do
        post 'add/:id', to: 'products#add_to_basket'
        post 'delete/:id', to: 'products#delete_from_basket'
        get 'add/:id', to: 'products#index'
        get 'delete/:id', to: 'products#index'
      end
    end

    resources :orders do
      collection do
      end
    end

    resources :roles do
      collection do
      end
    end
  end

  get '/registration', to: 'registration#new'
  post '/registration', to: 'registration#registration'
  get '/login', to: 'authentication#new'
  post '/login', to: 'authentication#create'
  get '/logout', to: 'authentication#destroy'

  get '/basket', to: 'baskets#index'
  post '/basket/add/:id', to: 'baskets#add'
  post '/basket/delete/:id', to: 'baskets#remove'
  get '/basket/add/:id', to: 'baskets#index'
  get '/basket/delete/:id', to: 'baskets#index'
  post '/basket/clear', to: 'baskets#clear'

  get '/checkout', to: 'checkout#new'
  post '/checkout', to: 'checkout#create'

  get '/products/:id', to: 'products#show'
  post 'add/:id', to: 'products#add_to_basket'
  post 'delete/:id', to: 'products#delete_from_basket'
  get 'add/:id', to: 'products#index'
  get 'delete/:id', to: 'products#index'

  root 'products#index'
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
  has_many :products, through: :order_products

  belongs_to :user
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < AdminsController
    before_action :authorize_admin

    def index
      @orders = Order.all
    end

    def show
      @order = Order.find(params[:id])
      make_products_array
    end

    def new
      @products = @basket.all
      @order = Order.new
      @user = User.find(session['warden.user.user.key'][0][0])
    end

    def create
      @order = Order.new(order_params)

      if @order.valid?
        @order.save!
        redirect_to admin_order_path(@order.id)
      else
        @products = @basket.all
        @user = User.find(session['warden.user.user.key'][0][0])
        render :new, status: :unprocessable_entity
      end

    end

    def edit
      @order = Order.find(params[:id])
      make_products_array
    end

    def update
      @order = Order.find(params[:id])

      if @order.update(order_params)
        redirect_to admin_order_path(params[:id])
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @order_products = OrderProduct.find_by(order_id: params[:id])
      @order = Order.find_by_id(params[:id])
      @order&.destroy

      redirect_to admin_orders_path
    end

    private

    def order_params
      params.require(:order).permit(:user_id, :order_price, :dest_address, :name, :phone_number)
    end

    def make_products_array
      @products = Product.joins(:order_products).where(order_products: { order_id: @order.id })
    end
  end
end

app/views/admin/orders/edit.html.erb
<div class="container">
  <div id="notification"></div>

  <div id="content">

    <ol class="breadcrumb">
      <li><a href="<%= admin_products_path %>">Home</a></li>
      <li><a href="<%= basket_path %>">Basket</a></li>
      <li><a href="<%= checkout_path %>">Checkout</a></li>
    </ol>

    <div class="page-header">
      <h1>Checkout</h1>
    </div>

    <%= simple_form_for @order, url: admin_order_path(@order) do |form| %>
      <div class="checkout panel-group">
        <div id="checkout" class="panel panel-default">
          <div class="checkout-heading panel-heading">Step 1: Name Options</div>
          <div class="checkout-content panel-body">

            <div class="form-group">
              <%= form.input :name, label: 'Add Name To Your Order', input_html: { value: @order.name, class: 'form-control' } %>
            </div>

          </div>
        </div>

        <div id="checkout" class="panel panel-default">
          <div class="checkout-heading panel-heading">Step 2: Phone Options</div>
          <div class="checkout-content panel-body">

            <div class="form-group">
              <%= form.input :phone_number, label: 'Add Phone To Your Order', input_html: { value: @order.phone_number, class: 'form-control' } %>
            </div>

          </div>
        </div>

        <div id="checkout" class="panel panel-default">
          <div class="checkout-heading panel-heading">Step 3: Address Options</div>
          <div class="checkout-content panel-body">

            <div class="form-group">
              <%= form.input :dest_address, label: 'Add Destination Address To Your Order', input_html: { value: @order.dest_address, class: 'form-control' } %>
            </div>

          </div>
        </div>

        <div id="confirm" class="panel panel-default">
          <div class="checkout-heading panel-heading">Step 4: Confirm Order</div>
          <div class="checkout-content panel-body">
            <div class="checkout-product table-responsive">
              <table class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th class="name">Product Name</th>
                  <th class="model">Model</th>
                  <th class="quantity">Quantity</th>
                  <th class="price">Price</th>
                  <th class="total">Total</th>
                </tr>
                </thead>

                <tbody>
                <% @products.uniq.each do |product| %>
                  <tr>
                    <td class="name">
                      <a href="/products/<%= product['id'] %>"><%= product['name'] %></a>
                      <br>
                    </td>
                    <td class="model"><img src="<%= product.photo %>" alt="<%= product['name'] %>"></td>
                    <td class="quantity"><%= @products.count(product) %></td>
                    <td class="price"><%= product['price'] %></td>
                    <td class="total"><input name="order[order_price]" type="hidden" value="<%= product['price']*@products.count(product) %>"><%= product['price']*@products.count(product) %></td>
                  </tr>
                <% end %>
                </tbody>

                <tfoot>

                <tr>
                  <td colspan="4" class="price text-right">
                    <b>Total:</b>
                  </td>
                  <td class="total"><%= @order.order_price %></td>
                </tr>
                </tfoot>
              </table>
            </div>
            <br>
            <div class="payment">
              <div class="buttons">
                <%= form.button :button, "Edit Order", type: "submit", class: "btn btn-warning" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>


  </div>
</div>

app/views/admin/orders/index.html.erb
<div id="container" class="content">
  <div class="container">
    <div id="notification"></div>

    <div id="content">
      <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
      </ol>

      <div class="box-product product-list">

        <% @orders.each do |order| %>
          <div class="item">
            <div class="caption">
              <div class="name">
                <a href="<%= admin_order_path(order) %>"><%= order.name %> (by <%= order.user.name %>)</a>
              </div>
              <div class="description">
                <%= order.dest_address %>
              </div>

              <div class="price">
                <div>
                  <span class="price-fixed"><%= order.order_price %> BTC</span>
                </div>
              </div>

              <a class="btn btn-danger tooltip-right" title="" href="<%= edit_admin_order_path(order) %>">
                <i class="fa fa-heart-o"></i> <span>Edit</span>
              </a>

              <a class="btn btn-link" href="<%= admin_order_path(order) %>" data-method="delete">
                <i class="fa fa-files-o"></i> <span>Delete</span>
              </a>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/admin/orders/new.html.erb
<div class="container">
  <div id="notification"></div>

  <div id="content">

    <ol class="breadcrumb">
      <li><a href="<%= admin_products_path %>">Home</a></li>
      <li><a href="<%= basket_path %>">Basket</a></li>
      <li><a href="<%= checkout_path %>">Checkout</a></li>
    </ol>

    <div class="page-header">
      <h1>Checkout</h1>
    </div>

    <%= simple_form_for :order, url: '/checkout' do |form| %>
      <div class="checkout panel-group">
        <div id="checkout" class="panel panel-default">
          <div class="checkout-heading panel-heading">Step 1: Name Options</div>
          <div class="checkout-content panel-body">

            <div class="form-group">
              <%= form.input :name, label: 'Add Name To Your Order', input_html: { value: @user.name, class: 'form-control' } %>
            </div>

          </div>
        </div>

        <div id="checkout" class="panel panel-default">
          <div class="checkout-heading panel-heading">Step 2: Phone Options</div>
          <div class="checkout-content panel-body">

            <div class="form-group">
              <%= form.input :phone_number, label: 'Add Phone To Your Order', input_html: { value: @user.phone_number, class: 'form-control' } %>
            </div>

          </div>
        </div>

        <div id="checkout" class="panel panel-default">
          <div class="checkout-heading panel-heading">Step 3: Address Options</div>
          <div class="checkout-content panel-body">

            <div class="form-group">
              <%= form.input :dest_address, label: 'Add Destination Address To Your Order', input_html: { class: 'form-control' } %>
            </div>

          </div>
        </div>

        <div id="confirm" class="panel panel-default">
          <div class="checkout-heading panel-heading">Step 4: Confirm Order</div>
          <div class="checkout-content panel-body">
            <div class="checkout-product table-responsive">
              <table class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th class="name">Product Name</th>
                  <th class="model">Model</th>
                  <th class="quantity">Quantity</th>
                  <th class="price">Price</th>
                  <th class="total">Total</th>
                </tr>
                </thead>

                <tbody>
                <% @products.uniq.each do |product| %>
                  <tr>
                    <td class="name">
                      <a href="/products/<%= product['id'] %>"><%= product['name'] %></a>
                      <br>
                    </td>
                    <td class="model"><img src="<%= product['photo']['url'] %>" alt="<%= product['name'] %>"></td>
                    <td class="quantity"><%= @products.count(product) %></td>
                    <td class="price"><%= product['price'] %></td>
                    <td class="total"><input name="order[order_price]" type="hidden" value="<%= product['price']*@products.count(product) %>"><%= product['price']*@products.count(product) %></td>
                  </tr>
                <% end %>
                </tbody>

                <tfoot>

                <tr>
                  <td colspan="4" class="price text-right">
                    <b>Sub-Total:</b>
                  </td>
                  <td class="total"><%= @basket.sum %></td>
                </tr>
                <tr>
                  <td colspan="4" class="price text-right">
                    <b>НДС 20%:</b>
                  </td>
                  <td class="total"><%= @basket.sum*0.2 %></td>
                </tr>
                <tr>
                  <td colspan="4" class="price text-right">
                    <b>Total:</b>
                  </td>
                  <td class="total"><%= @basket.sum*1.2 %></td>
                </tr>
                </tfoot>
              </table>
            </div>
            <br>
            <div class="payment">
              <div class="buttons">
                <%= form.button :button, "Confirm Order", type: "submit", class: "btn btn-warning" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>


  </div>
</div>

app/views/admin/orders/show.html.erb
<div id="container" class="content">
  <div class="container">
    <div id="notification"></div>

    <div id="content">
      <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
      </ol>

      <div class="box-product product-list">

        <div class="item">
          <div class="caption">
            <div class="name">
              <a href="<%= admin_user_path(@order.user) %>"><%= @order.name %> (by <%= @order.user.name %>)</a>
            </div>
            <div class="description">
              <%= @order.dest_address %>
            </div>

            <div class="price">
              <div>
                <span class="price-fixed"><%= @order.order_price %> BTC</span>
              </div>
            </div>

            <a class="btn btn-danger tooltip-right" title="" href="<%= edit_admin_order_path(@order) %>">
              <i class="fa fa-heart-o"></i> <span>Edit</span>
            </a>

            <a class="btn btn-link" href="<%= admin_order_path(@order) %>" data-method="delete">
              <i class="fa fa-files-o"></i> <span>Delete</span>
            </a>
          </div>
        </div>

        <% @products.uniq.each do |product| %>
          <div class="item">
            <div class="image">
              <img src="<%= product.photo %>" title="<%= product.name %>" alt="<%= product.name %>">
            </div>
            <div class="caption">
              <div class="name">
                <a href="<%= admin_product_path(product) %>"><%= product.name %></a>
              </div>
              <div class="description">
                <%= product.description %>
              </div>

              <div class="price">
                <div>
                  <span class="price-fixed"><%= @products.count { |product_from_array| product.id == product_from_array.id } %> X <%= product.price %> BTC</span>
                </div>
              </div>

            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>