config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'}
  #devise_for :users, controllers: {sessions: 'sessions'}
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :users do
      collection do
      end
    end

    resources :products do
      collection do
        post 'add/:id', to: 'products#add_to_basket'
        post 'delete/:id', to: 'products#delete_from_basket'
        get 'add/:id', to: 'products#index'
        get 'delete/:id', to: 'products#index'
      end
    end

    resources :orders do
      collection do
      end
    end

    resources :roles do
      collection do
      end
    end
  end

  get '/registration', to: 'registration#new'
  post '/registration', to: 'registration#registration'
  get '/login', to: 'authentication#new'
  post '/login', to: 'authentication#create'
  get '/logout', to: 'authentication#destroy'

  get '/basket', to: 'baskets#index'
  post '/basket/add/:id', to: 'baskets#add'
  post '/basket/delete/:id', to: 'baskets#remove'
  get '/basket/add/:id', to: 'baskets#index'
  get '/basket/delete/:id', to: 'baskets#index'
  post '/basket/clear', to: 'baskets#clear'

  get '/checkout', to: 'checkout#new'
  post '/checkout', to: 'checkout#create'

  get '/products/:id', to: 'products#show'
  post 'add/:id', to: 'products#add_to_basket'
  post 'delete/:id', to: 'products#delete_from_basket'
  get 'add/:id', to: 'products#index'
  get 'delete/:id', to: 'products#index'

  root 'products#index'
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/controllers/admin/roles_controller.rb
module Admin
  class RolesController < AdminsController
    before_action :authorize_admin

    def index
      @roles = Role.all
    end

    def show
      @role = Role.find(params[:id])
    end

    def new
      @role = Role.new
    end

    def create
      @role = Role.new(role_params)

      if @role.valid?
        @role.save!
        redirect_to admin_role_path(@role.id)
      else
        render :new, status: :unprocessable_entity
      end

    end

    def edit
      @role = Role.find(params[:id])
    end

    def update
      @role = Role.find(params[:id])

      if @role.update(role_params)
        redirect_to admin_role_path(params[:id])
      else
        @role = Role.find(params[:id])
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @role = Role.find_by_id(params[:id])
      @role&.destroy
      redirect_to admin_roles_path
    end

    private

    def role_params
      params.require(:role).permit(:name)
    end
  end
end

app/views/admin/roles/edit.html.erb
<div id="container" class="content">
  <div class="container">
    <div id="notification"></div>

    <div id="content">
      <ol class="breadcrumb">
        <li><a href="<%= admin_products_path %>">Home</a></li>
        <li><a href="<%= admin_roles_path %>">Roles</a></li>
      </ol>

      <div class="page-header">
        <h1>Update role</h1>
      </div>

      <%= simple_form_for @role, url: admin_role_path(@role) do |form| %>
        <div class="row">
          <div class="col-sm-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Role's Details</h3>
              </div>
              <div class="panel-body">
                <div class="content">

                  <div class="form-group  ">
                    <%= form.input :name, input_html: { class: 'form-control' }, label: ' Name:', label_html: { class: 'label-control' } %>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default">
              <div class="panel-body">

                <input type="submit" value="Continue" class="btn btn-warning">
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/admin/roles/index.html.erb
<div id="container" class="content">
  <div class="container">
    <div id="notification"></div>

    <div id="content">
      <ol class="breadcrumb">
        <li><a href="<%= admin_products_path %>">Home</a></li>
        <li><a href="<%= new_admin_role_path %>">Add role</a></li>
      </ol>

      <div class="box-product product-list">
        <% @roles.each do |role| %>
          <div class="item">
            <div class="caption">
              <div class="name">
                <a href="<%= admin_role_path(role) %>"><%= role.name %></a>
              </div>

              <a class="btn btn-danger tooltip-right" title="" href="<%= edit_admin_role_path(role) %>">
                <i class="fa fa-heart-o"></i> <span>Edit</span>
              </a>

              <a class="btn btn-link" href="<%= admin_role_path(role) %>" data-method="delete">
                <i class="fa fa-files-o"></i> <span>Delete</span>
              </a>
            </div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/admin/roles/new.html.erb
<div id="container" class="content">
  <div class="container">
    <div id="notification"></div>

    <div id="content">
      <ol class="breadcrumb">
        <li><a href="<%= admin_products_path %>">Home</a></li>
        <li><a href="<%= admin_roles_path %>">Roles</a></li>
      </ol>

      <div class="page-header">
        <h1>New role</h1>
      </div>

      <%= simple_form_for @role, url: '/admin/roles' do |form| %>
        <div class="row">
          <div class="col-sm-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Role's Details</h3>
              </div>
              <div class="panel-body">
                <div class="content">

                  <div class="form-group  ">
                    <%= form.input :name, input_html: { class: 'form-control' }, label: ' Name:', label_html: { class: 'label-control' } %>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default">
              <div class="panel-body">

                <input type="submit" value="Continue" class="btn btn-warning">
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/admin/roles/show.html.erb
<div id="container" class="content">
  <div class="container">
    <div id="notification"></div>

    <div id="content">
      <ol class="breadcrumb">
        <li><a href="<%= admin_products_path %>">Home</a></li>
        <li><a href="<%= new_admin_role_path %>">Add role</a></li>
      </ol>

      <div class="box-product product-list">
        <div class="item">
          <div class="caption">
            <div class="name">
              <a href="<%= admin_role_path(@role) %>"><%= @role.name %></a>
            </div>

            <a class="btn btn-danger tooltip-right" title="" href="<%= edit_admin_role_path(@role) %>">
              <i class="fa fa-heart-o"></i> <span>Edit</span>
            </a>

            <a class="btn btn-link" href="<%= admin_role_path(@role) %>" data-method="delete">
              <i class="fa fa-files-o"></i> <span>Delete</span>
            </a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>