config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'}
  #devise_for :users, controllers: {sessions: 'sessions'}
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :users do
      collection do
      end
    end

    resources :products do
      collection do
        post 'add/:id', to: 'products#add_to_basket'
        post 'delete/:id', to: 'products#delete_from_basket'
        get 'add/:id', to: 'products#index'
        get 'delete/:id', to: 'products#index'
      end
    end

    resources :orders do
      collection do
      end
    end

    resources :roles do
      collection do
      end
    end
  end

  get '/registration', to: 'registration#new'
  post '/registration', to: 'registration#registration'
  get '/login', to: 'authentication#new'
  post '/login', to: 'authentication#create'
  get '/logout', to: 'authentication#destroy'

  get '/basket', to: 'baskets#index'
  post '/basket/add/:id', to: 'baskets#add'
  post '/basket/delete/:id', to: 'baskets#remove'
  get '/basket/add/:id', to: 'baskets#index'
  get '/basket/delete/:id', to: 'baskets#index'
  post '/basket/clear', to: 'baskets#clear'

  get '/checkout', to: 'checkout#new'
  post '/checkout', to: 'checkout#create'

  get '/products/:id', to: 'products#show'
  post 'add/:id', to: 'products#add_to_basket'
  post 'delete/:id', to: 'products#delete_from_basket'
  get 'add/:id', to: 'products#index'
  get 'delete/:id', to: 'products#index'

  root 'products#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy

  rolify

  has_paper_trail
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminsController
    before_action :authorize_admin

    def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)

      if @user.valid?
        @user.save!
        redirect_to admin_user_path(@user.id)
      else
        render :new, status: :unprocessable_entity
      end

    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])

      @user.paper_trail_event = 'update'
      if @user.update(user_params)
        redirect_to admin_user_path(params[:id])
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @user = User.find_by_id(params[:id])
      @user&.destroy
      redirect_to admin_users_path
    end

    private

    def user_params
      params.require(:user).permit(:name, :password, :email, :password_confirmation, :phone_number)
    end
  end
end

app/views/admin/users/edit.html.erb
<div id="container" class="content">
  <div class="container">
    <div id="notification"></div>

    <div id="content">
      <ol class="breadcrumb">
        <li><a href="<%= admin_products_path %>">Home</a></li>
        <li><a href="<%= admin_users_path %>">Users</a></li>
      </ol>

      <div class="page-header">
        <h1>Update user</h1>
      </div>

      <%= simple_form_for @user, url: admin_user_path(@user) do |form| %>
        <div class="row">
          <div class="col-sm-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Your Personal Details</h3>
              </div>
              <div class="panel-body">
                <div class="content">
                  <div class="form-group  ">
                    <%= form.input :name, input_html: { class: 'form-control' }, label: ' Name:', label_html: { class: 'label-control' } %>
                  </div>

                  <div class="form-group  ">
                    <div class="form-group  ">
                      <%= form.input :email, input_html: { class: 'form-control' }, label: ' Email:', label_html: { class: 'label-control' } %>
                    </div>
                  </div>

                  <div class="form-group  ">
                    <div class="form-group  ">
                      <%= form.input :phone_number, input_html: { class: 'form-control' }, label: ' Telephone:', label_html: { class: 'label-control' } %>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Your Password</h3>
              </div>
              <div class="panel-body">
                <div class="content">

                  <div class="form-group  ">
                    <%= form.input :password, input_html: { class: 'form-control' }, label: ' Password:', label_html: { class: 'label-control' } %>
                  </div>

                  <div class="form-group  ">
                    <%= form.input :password_confirmation, input_html: { class: 'form-control' }, label: ' Confirm password:', label_html: { class: 'label-control' } %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default">
              <div class="panel-body">

                <input type="submit" value="Continue" class="btn btn-warning">
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/admin/users/index.html.erb
<div id="container" class="content">
  <div class="container">
    <div id="notification"></div>

    <div id="content">
      <ol class="breadcrumb">
        <li><a href="<%= admin_products_path %>">Home</a></li>
        <li><a href="<%= new_admin_user_path %>">Add user</a></li>
      </ol>

      <div class="box-product product-list">
        <% @users.each do |user| %>
          <div class="item">
            <div class="caption">
              <div class="name">
                <a href="<%= admin_user_path(user) %>"><%= user.name %></a>
              </div>
              <div class="description">
                <%= user.email %>
              </div>

              <div class="price">
                <div>
                  <span class="price-fixed"><%= user.phone_number %></span>
                </div>
              </div>

              <a class="btn btn-danger tooltip-right" title="" href="<%= edit_admin_user_path(user) %>">
                <i class="fa fa-heart-o"></i> <span>Edit</span>
              </a>

              <a class="btn btn-link" href="<%= admin_user_path(user) %>" data-method="delete">
                <i class="fa fa-files-o"></i> <span>Delete</span>
              </a>
            </div>
          </div>
        <% end %>

      </div>

      <script type="text/javascript">
          function display(view) {
              if (view == 'list')
              {
                  $('#content .product-grid').attr('class', 'product-list box-product');
                  $('.display').html('' +
                      '<div class="btn-group btn-group-sm">' +
                      '<span class="btn btn-default" disabled="disabled"><i class="fa fa-th-list"></i> List</span>' +
                      '<a class="btn btn-default" onclick="display(\'grid\');"><i class="fa fa-th"></i> Grid</a>' +
                      '</div>'
                  );
                  $.totalStorage('display', 'list');
              }
              else
              {
                  $('#content .product-list').attr('class', 'product-grid box-product');
                  $('.display').html('' +
                      '<div class="btn-group btn-group-sm">' +
                      '<a class="btn btn-default" onclick="display(\'list\');"><i class="fa fa-th-list"></i> List</a>' +
                      '<span class="btn btn-default" disabled="disabled"><i class="fa fa-th"></i> Grid</span>' +
                      '</div>'
                  );
                  $.totalStorage('display', 'grid');
              }
          }
          view = $.totalStorage('display');
          if (view) {
              display(view);
          } else {
              display('list');
          }
      </script>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div id="container" class="content">
  <div class="container">
    <div id="notification"></div>

    <div id="content">
      <ol class="breadcrumb">
        <li><a href="<%= admin_products_path %>">Home</a></li>
        <li><a href="<%= admin_users_path %>">Users</a></li>
      </ol>

      <div class="page-header">
        <h1>New user</h1>
      </div>

      <%= simple_form_for @user, url: '/admin/users' do |form| %>
        <div class="row">
          <div class="col-sm-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Your Personal Details</h3>
              </div>
              <div class="panel-body">
                <div class="content">
                  <div class="form-group  ">
                    <%= form.input :name, input_html: { class: 'form-control' }, label: ' Name:', label_html: { class: 'label-control' } %>
                  </div>

                  <div class="form-group  ">
                    <div class="form-group  ">
                      <%= form.input :email, input_html: { class: 'form-control' }, label: ' Email:', label_html: { class: 'label-control' } %>
                    </div>
                  </div>

                  <div class="form-group  ">
                    <div class="form-group  ">
                      <%= form.input :phone_number, input_html: { class: 'form-control' }, label: ' Telephone:', label_html: { class: 'label-control' } %>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Your Password</h3>
              </div>
              <div class="panel-body">
                <div class="content">

                  <div class="form-group  ">
                    <%= form.input :password, input_html: { class: 'form-control' }, label: ' Password:', label_html: { class: 'label-control' } %>
                  </div>

                  <div class="form-group  ">
                    <%= form.input :password_confirmation, input_html: { class: 'form-control' }, label: ' Confirm password:', label_html: { class: 'label-control' } %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default">
              <div class="panel-body">

                <input type="submit" value="Continue" class="btn btn-warning">
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/admin/users/show.html.erb
<div id="container" class="content">
  <div class="container">
    <div id="notification"></div>

    <div id="content">
      <ol class="breadcrumb">
        <li><a href="<%= admin_products_path %>">Home</a></li>
      </ol>

      <div class="box-product product-list">
        <div class="item">
          <div class="caption">
            <div class="name">
              <a href="<%= admin_user_path(@user) %>"><%= @user.name %></a>
            </div>
            <div class="description">
              <%= @user.email %>
            </div>

            <div class="price">
              <div>
                <span class="price-fixed"><%= @user.phone_number %></span>
              </div>
            </div>

            <a class="btn btn-danger tooltip-right" title="" href="<%= edit_admin_user_path(@user) %>">
              <i class="fa fa-heart-o"></i> <span>Edit</span>
            </a>

            <a class="btn btn-link" href="<%= admin_user_path(@user) %>" data-method="delete">
              <i class="fa fa-files-o"></i> <span>Delete</span>
            </a>
          </div>
        </div>
      </div>

    </div>

    <script type="text/javascript">
        function display(view) {
            if (view == 'list')
            {
                $('#content .product-grid').attr('class', 'product-list box-product');
                $('.display').html('' +
                    '<div class="btn-group btn-group-sm">' +
                    '<span class="btn btn-default" disabled="disabled"><i class="fa fa-th-list"></i> List</span>' +
                    '<a class="btn btn-default" onclick="display(\'grid\');"><i class="fa fa-th"></i> Grid</a>' +
                    '</div>'
                );
                $.totalStorage('display', 'list');
            }
            else
            {
                $('#content .product-list').attr('class', 'product-grid box-product');
                $('.display').html('' +
                    '<div class="btn-group btn-group-sm">' +
                    '<a class="btn btn-default" onclick="display(\'list\');"><i class="fa fa-th-list"></i> List</a>' +
                    '<span class="btn btn-default" disabled="disabled"><i class="fa fa-th"></i> Grid</span>' +
                    '</div>'
                );
                $.totalStorage('display', 'grid');
            }
        }
        view = $.totalStorage('display');
        if (view) {
            display(view);
        } else {
            display('list');
        }
    </script>
  </div>
</div>