config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'}
  #devise_for :users, controllers: {sessions: 'sessions'}
  mount Sidekiq::Web => '/sidekiq'

  namespace :admin do
    resources :users do
      collection do
      end
    end

    resources :products do
      collection do
        post 'add/:id', to: 'products#add_to_basket'
        post 'delete/:id', to: 'products#delete_from_basket'
        get 'add/:id', to: 'products#index'
        get 'delete/:id', to: 'products#index'
      end
    end

    resources :orders do
      collection do
      end
    end

    resources :roles do
      collection do
      end
    end
  end

  get '/registration', to: 'registration#new'
  post '/registration', to: 'registration#registration'
  get '/login', to: 'authentication#new'
  post '/login', to: 'authentication#create'
  get '/logout', to: 'authentication#destroy'

  get '/basket', to: 'baskets#index'
  post '/basket/add/:id', to: 'baskets#add'
  post '/basket/delete/:id', to: 'baskets#remove'
  get '/basket/add/:id', to: 'baskets#index'
  get '/basket/delete/:id', to: 'baskets#index'
  post '/basket/clear', to: 'baskets#clear'

  get '/checkout', to: 'checkout#new'
  post '/checkout', to: 'checkout#create'

  get '/products/:id', to: 'products#show'
  post 'add/:id', to: 'products#add_to_basket'
  post 'delete/:id', to: 'products#delete_from_basket'
  get 'add/:id', to: 'products#index'
  get 'delete/:id', to: 'products#index'

  root 'products#index'
end

app/views/layouts/_footer.html.erb
<div id="footer" class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="column">
          <h4>Information</h4>
          <ul>
            <li><a href="">About Us</a></li>
            <li><a href="">Wide page</a></li>
            <li><a href="">Right column</a></li>
            <li><a href="">Typography </a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="column">
          <h4>Customer Service</h4>
          <ul>
            <li><a href="">Contact Us</a></li>
            <li><a href="">Returns</a></li>
            <li><a href="">Site Map</a></li>
          </ul>
        </div>
      </div>
      <% if (user = current_user) && (user.has_role? :admin) %>
        <div class="col-sm-3">
          <div class="column">
            <h4>Admin</h4>
            <ul>
              <li><a href="<%= admin_users_path %>">Users</a></li>
              <li><a href="<%= admin_products_path %>">Products</a></li>
              <li><a href="<%= admin_orders_path %>">Orders</a></li>
              <li><a href="<%= admin_roles_path %>">Roles</a></li>
            </ul>
          </div>
        </div>
      <% else %>
        <div class="col-sm-3">
          <div class="column">
            <h4>Menu</h4>
            <ul>
              <li><a href="/">Products</a></li>
            </ul>
          </div>
        </div>
      <% end %>
      <div class="col-sm-3">
        <div class="column">
          <h4>My Account</h4>
          <ul>
            <% unless current_user %>
              <li><a href="<%= new_user_session_path %>">Login</a></li>
              <li><a href="<%= new_user_registration_path %>">Register</a></li>
            <% end %>
            <li><a href="<%= basket_path %>">Basket</a></li>
            <li><a href="<%= checkout_path %>">Checkout</a></li>
            <% if current_user %>
              <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-sm-9 ">
        <div id="about">
          <h3>Order pizza online</h3>
          <p>
                               <span id="result_box" lang="en">
                                    <span class="hps">You are welcome to site</span>
                                    <span class="hps">of pizza </span>
                                    <span class="hps">and Japanese cuisine</span>
                                    <span class="hps">in your city.</span>
                                    <span class="hps">Here you always</span>
                                    <span class="hps">can order&nbsp;</span>
                                    <span class="hps">pizza,</span>
                                    <span class="hps">sushi, rolls</span>
                                    <span class="hps">and beverages for home delivery.</span>
                                    <span class="hps">Pepperoni</span>
                                    <span>,</span>
                                    <span class="hps">Margarita</span>
                                    <span>, 4</span>
                                    <span class="hps">cheese</span>
                                    <span class="hps">and others.</span>
                                    <span class="hps">In the menu</span>
                                    <span class="hps">of Japanese cuisine</span>
                                    <span class="hps">you can order</span>
                                    <span class="hps">sushi with</span>
                                    <span class="hps">salmon and eel</span>
                                    <span>, classic</span>
                                    <span class="hps">California</span>
                                    <span class="hps">and</span>
                                    <span class="hps">Philadelphia </span>
                                </span>
            <span id="result_box" lang="en">
                                    <span class="hps">rolls</span>
                                    <span>,</span>
                                    <span class="hps">as well as</span>
                                    <span class="hps">warm rolls</span>
                                    <span class="hps">Tempura</span>
                                    <span>.</span>
                                    <span class="hps">You will be pleased</span>
                                    <span class="hps">with the</span>
                                    <span class="hps">new </span>
                                    <span class="hps">sushi</span>
                                    <span class="hps">with spicy and</span>
                                    <span class="hps">fragrant sauce</span>
                                    <span>.</span>
                                    <span class="hps">Free</span>
                                    <span class="hps">pizza </span>
                                </span>
            <span id="result_box" lang="en">
                                    <span class="hps">and Japanese cuisine </span>
                                    <span>delivery</span>
                                    <span> in your city </span>
                                    <span class="hps">.</span>
                                </span>
          </p>
        </div>
      </div>
      <div class="col-sm-3 text-right">
        <div id="powered">
          <a href="https://gitlab.com/dan_kushaet_banan" title="Dan's Gitlab">Designed by Dan</a>
          <br>
          Krypto Pizza © 2021
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header" style="margin-top: 100px">
  <div class="container">

    <div class="row">
      <div class="col-sm-4">
        <div class="header-left">
          <div id="address">
            <p><strong>Hours of operation:</strong></p>
            <p>mon.-fr. <strong>12:00 - 18:00</strong>, sat.-sun. <strong>9:00 - 19:00</strong></p>
          </div>
          <div id="phone"><span>(044)</span> 512-67-77</div>
        </div>
      </div>

      <div class="col-sm-4">
        <div id="logo">
          <a href="<%= root_path %>"><img src="/img/logo_pizza.png" title="Crypto Pizza" alt="Crypto Pizza"></a>
        </div>
      </div>

      <div class="col-sm-4">
        <div id="search">
          <div class="input-group">
            <input type="text" name="search" class="form-control" placeholder="Search" value="">
            <span class="input-group-btn">
                                    <button class="btn btn-default button-search" type="button"><span class="fa fa-search"></span></button>
                                </span>
          </div>
        </div>

        <div class="header-right">
          <div id="welcome">
            Welcome visitor you can <a href="<%= user_session_path %>">login</a> or <a href="<%= new_user_registration_path %>">create an account</a>.
          </div>

          <div class="links">
            <a id="link-cart" href="<%= basket_path %>">
              <i class="fa fa-shopping-cart"></i> Basket
            </a><br>
            <a id="link-checkout" href="<%= checkout_path %>">
              <i class="fa fa-credit-card"></i> Checkout
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top topbar">
  <div class="container">

    <!-- cart -->
    <div id="cart">
      <div class="heading">
        <a title="Shopping Cart" href="<%= basket_path %>">
                           <span id="cart-total">
                               <i class="fa fa-shopping-cart fa-lg"></i>&nbsp;
                               <span class="hidden-xs"><%= @basket.size %> item(s) - <%= @basket.sum %> BTC</span>
                           </span>
        </a>
      </div>

      <div class="content">
        <div class="inner">
          <div class="empty">Your shopping cart is empty!</div>
        </div>
      </div>
    </div>

    <!-- menu -->
    <div id="menu" class="menu-container">
      <button type="button" class="menu-toggle" data-toggle="collapse" data-target="#menu-mobile">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="collapse menu-collapse" id="menu-mobile">
        <ul class="nav nav-pills">
          <li><a href="/">Pizza</a></li>
        </ul>
      </div>
    </div>
    <div class="divider hidden-sm hidden-xs"></div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Krypto Pizza</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render partial: '/layouts/navbar' %>

<%= render partial: '/layouts/header' %>

<%= yield %>

<%= render partial: '/layouts/footer' %>
</body>

</html>